language: perl
# Use container-based infrastucture on Travis which doesn't support running
# things as root; see http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
perl:
    - "5.16"
    - "5.18"
    - "5.20"
    #
    # Do not test on Perl 5.19 because 5.19.9 seems to mishandle UTF-8 source files
    # (see https://travis-ci.org/berkmancenter/mediacloud/jobs/28721908#L2803);
    # Perl 5.18 and 5.20 work fine though.
    #
    #- "5.19"
addons:
    postgresql: "9.3"
    hosts:
        - mediacloud.local
    apt:
        # Whitelist: https://github.com/travis-ci/apt-source-whitelist
        sources:
            # We need an up-to-date version of Gearman
            - gearman-developers
            # ...and a recent version of MongoDB too
            - mongodb-upstart
        # Whitelist: https://github.com/travis-ci/apt-package-whitelist
        # Keep in sync with "install_mediacloud_system_package_dependencies.sh"
        packages:
            - build-essential
            - cpanminus
            - curl
            - g++
            - gawk
            - gcc
            - graphviz
            - graphviz-dev
            - libdb-dev
            - libexpat1
            - libexpat1-dev
            - libgearman-dev
            - libgraph4
            - libgraphviz-dev
            - libxml2-dev
            - libxslt1-dbg
            - libxslt1-dev
            - libxslt1.1
            - libyaml-0-2
            - libyaml-dev
            - make
            - mongodb-10gen
            - netcat
            - openjdk-7-jdk
            - openjdk-7-jre-headless
            - pandoc
            - postgresql-server-dev-all
            - python-dev
            - python-software-properties
            - python-virtualenv
            - tidy
cache:
    directories:
        # Carton dependencies
        - local/
env:
    global:
        # Facebook Graph API credentials for testing
        - secure: "BgP5lOHOeb/Bv92o3ItUxRzzV1/aRCSMlAqTEf1ox1pniYmRhHB1+8P21QOPbMH6bxm2uaBhnPOKCQ8b37SmFk/TNBuXZyec4d1deGB+0u4N4bPX4MN7Q9f9IV1PxEVjr3dIzKtdpuTM9giNK/R9HpjYIftZw6UT+nyWufJ7hZg="
        - secure: "TrvXE5MJHDZb8a0KfnnElEqKZYXPpYSNGQO7ZtDAMC71B4CSthgr1beBxFkd9qSqFP304dLSIVWAs2Rhe9FahIwFIBcrLYlpoYCq8rTZo2txC+Xvg9qgP4uM59s83fYHeD7AfWFsIleYhV4gRsF8ZFxsPhf2IgVyH1mTGVaZyEU="
before_install:
    # Set up local Media Cloud environment for Python
    - mkdir $HOME/mc-python
    - virtualenv $HOME/mc-python
    - source $HOME/mc-python/bin/activate
    # Travis artifacts (for caching "local/" to S3)
    - travis_retry gem install fog-json
    - travis_retry gem install travis-artifacts
    # Create + switch to the Media Cloud's Perlbrew library
    - perlbrew lib create mediacloud
    - perlbrew switch @mediacloud
    # Install Media Cloud system package dependencies
    - ./install_modules_outside_of_carton.sh
    # Rerun Carton on (cached) "local/" directory
    - ./install_modules_with_carton.sh
    # Install Python dependencies
    - travis_retry pip install -r python_scripts/requirements.txt
    # install Media Cloud testing variant of the Python  Client
    - travis_retry git clone https://github.com/dlarochelle/MediaCloud-API-Client.git
    - travis_retry easy_install MediaCloud-API-Client/
    # Install Supervisor
    - easy_install supervisor
install:
    # Use default configuration
    - cp mediawords.yml.dist mediawords.yml
    # Create PostgreSQL database
    - ./install_scripts/create_default_db_user_and_databases.sh
before_script:
    # Initialize PostgreSQL database
    - MEDIAWORDS_CREATE_DB_DO_NOT_CONFIRM=1 ./script/run_with_carton.sh ./script/mediawords_create_db.pl
script:
    # Run Media Cloud's test suite, report test coverage to https://coveralls.io/r/berkmancenter/mediacloud
    - MEDIACLOUD_ENABLE_PYTHON_API_TESTS=1 ./script/run_test_suite_for_devel_cover.sh coveralls --destroy-solr
after_failure:
    # Print out the test log
    - echo
    - echo "Unit test(s) have failed; here's the full log:"
    - echo
    - cat data/run_test_suite.log
