language: perl
perl:
    - "5.16"
addons:
    hosts:
        - mediacloud.local
install:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
    - sudo apt-get -y update
    - MEDIAWORDS_CREATE_DB_DO_NOT_CONFIRM=1 ./install.sh
script:
    - ./script/run_test_suite.sh
