language: perl
perl:
    - "5.16"
addons:
    hosts:
        - mediacloud.local
install:
    # Upgrade packages:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
    # Install Media Cloud and dependencies:
    - MEDIAWORDS_CREATE_DB_DO_NOT_CONFIRM=1 ./install.sh
script:
    # Run Media Cloud's test suite
    - ./script/run_test_suite.sh
