language: perl
# Installing up-to-date Erlang requires root
sudo: true
perl:
    - "5.22"
addons:
    postgresql: "9.3"
    hosts:
        - mediacloud.local
cache:
    directories:
        # Carton dependencies
        - local/
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
env:
    global:
        # Facebook Graph API credentials for testing:
        # * MC_FACEBOOK_APP_ID
        # * MC_FACEBOOK_APP_SECRET
        - secure: "TklAqxPSqywPk5khp54R7iYW9jGfuWYiVC7xY3wiO8GQHRpW3b0a6zR3yEbeBMvKMt5b1IaCCJwuyasP/W0xPopqozqJFr/6045/tfTqRQ7/Bo6noJ1a640yLjjDzlGenHqkTCbhp5y4kaT2BS1IoTi423FOXQB1OVTpVD55jAw="
        - secure: "A9bwQIK5W8VyQlpdnoA6LhKTcllytTS/8ueyzi9Y7F6xFdD2sFnfTy6UgpFIzgtVezYJYqy7Wcr1RiC3ybOmsE4FSYRTptrEdu4Pf/nI/LRxDE+sF2kPDGrXRD8iTL5+K2h5DMbBG2NsoflC+qRgn1W9f/Ey1gMsmCyOJJCnufw="
        # Amazon S3 test bucket credentials:
        # * MC_AMAZON_S3_TEST_ACCESS_KEY_ID
        # * MC_AMAZON_S3_TEST_SECRET_ACCESS_KEY
        # * MC_AMAZON_S3_TEST_BUCKET_NAME
        # * MC_AMAZON_S3_TEST_DIRECTORY_NAME
        - secure: "DpYY9zJCMOABwBUhW5tTLRjWgKKNgkWBH/i5x2hJTSkY53erpaaqTPzs/loGbiV1Q+TUu0PWPqRQh9eovDKd2/l2taXECbQi+gY/VprlYK4rqruLXci9mxJepIp9imITiCwxZB9hYI3BDxQYBvPDx0coklEi5bG017HZNlwYQfg="
        - secure: "ONqZb6dPH8uNcCVkLH722JPhP4Zua8QjbYcj24ob27LVrjh9UbSAUVMu+3XVczY0dERsGGcqH2bhaG3WYINAs0wnbyPfbAokHtRSrIcDfSfVkDfCzJkYl7jc1Dhc/lV/pe6ygqtGZQG+Whx/dKf6DpCJmpEekeHavwVDxzC1D+4="
        - secure: "Y3poZS6KCMfAyXmAG4hvHhCtaUHLl3UwB2CYjDLp2ki86tDtG7JfEJp2Q/8C610nzBw6WlA8bdljM9dxNHR6aEGHPxLz1NsGMLw8xYZFoMrw6RMpRq6BLcraylAmVZAFC2GTClqzHMWfW6mCQ5a5OznUWsJ6n4tP0aoPLjRpUgw="
        - secure: "GHU56Kl7zaE00MZeaPqie3e8xoxLaGnh3A03xZbG8/707tPtBsPLfPDaCSQf9PSstajVjPik+tUNuOTgyz9AD5ma3dwPdJ6VhpFNS/DD8+CDlojmgEfuvaVD7Bi3sLFuop/PWrNoi0pND45lv8O8shQ1WruHEWPgYxW10vd3Q7Y="
        # Do not ask for confirmation when running ./script/mediawords_create_db.pl
        - MEDIAWORDS_CREATE_DB_DO_NOT_CONFIRM=1
        # Enable Python API tests in ./script/run_test_suite_for_devel_cover.sh
        - MEDIACLOUD_ENABLE_PYTHON_API_TESTS=1
        # Test PythonReadability extractor method in t/test_extractor.t
        - MC_TEST_EXTRACTOR_PYTHONREADABILITY=1
before_install:
    # Set correct timezone
    - sudo ln -sf "/usr/share/zoneinfo/America/New_York" /etc/localtime
    - echo -n "America/New_York" | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - export TZ=America/New_York
    - date
    # Install APT packages
    - ./install_scripts/install_mediacloud_system_package_dependencies.sh
    # Set up local Media Cloud environment for Python
    - mkdir -p $HOME/mc-python
    - virtualenv $HOME/mc-python
    - source $HOME/mc-python/bin/activate
    # Install Python dependencies
    - travis_retry pip install --upgrade pip setuptools
    - travis_retry pip install --upgrade -r python_scripts/requirements.txt
    # Install Media Cloud testing variant of the Python Client
    - travis_retry git clone https://github.com/berkmancenter/mediacloud-api-testing-client.git MediaCloud-API-Client/
    - cd MediaCloud-API-Client/; git checkout v2.25.0-api-testing-cleanup; cd ../
    - travis_retry pip install --editable MediaCloud-API-Client/
    # Create + switch to the Media Cloud's Perlbrew library
    - perlbrew lib create mediacloud
    - perlbrew switch @mediacloud
    # Install Media Cloud system package dependencies
    - ./install_modules_outside_of_carton.sh
    # (Re)install Carton dependencies (which might be restored from cache into
    # "local/" already in which case we just check if Carton is happy with the
    # current setup)
    - ./install_modules_with_carton.sh
install:
    # Use default configuration
    - cp mediawords.yml.dist mediawords.yml
    # Create PostgreSQL database
    - ./install_scripts/create_default_db_user_and_databases.sh
before_script:
    # Initialize PostgreSQL database
    - ./script/run_with_carton.sh ./script/mediawords_create_db.pl
script:
    # Start Readability service for testing "PythonReadability" extractor method on t/test_extractor.t
    - "python python_scripts/extractor_python_readability_server.py &"
    # Run Media Cloud's test suite, report test coverage to https://coveralls.io/r/berkmancenter/mediacloud
    - ./script/run_test_suite_for_devel_cover.sh coveralls --destroy-solr
after_failure:
    # Print out the test log
    - echo
    - echo "Unit test(s) have failed; here's the full log:"
    - echo
    - cat data/run_test_suite.log
