---
Plugin::Authentication:
    default_realm: users
    users:
        credential:
            class: Password
            password_field: password
            password_hash_type: SHA-256
            password_salt_len: 64
            password_type: salted_hash
        store:
            class: MediaWords
gearman:
    servers:
        - "127.0.0.1:4731"
    notifications:
        emails: []
        from_address: gjs@mediacloud.org
        subject_prefix: '[GJS]'
    worker_log_dir: data/gearman_worker_logs/
mail:
    bug_email: ''
    from_address: noreply@mediacloud.org
mediawords:
    always_show_stack_traces: no
    controversy_model_reps: 25
    default_home_page: admin/media/list
    extractor_method: InlinePythonReadability
    language: en_US_and_ru_RU
    owner: mediacloud@cyber.law.harvard.edu
    download_storage_locations:
        - postgresql
    read_all_downloads_from_s3: no
    fallback_postgresql_downloads_to_s3: no
    cache_s3_downloads: no
    recaptcha_private_key: 6LfEVt0SAAAAABmI-8IJmx4g93eNcSeyeCxvLMs2
    recaptcha_public_key: 6LfEVt0SAAAAAFwQI0pOZ1bTHgDTpQcMeQY6VLd_
    solr_url:
        - "http://localhost:8983/solr"
    user_agent: mediawords bot (http://cyber.law.harvard.edu)
    cm_spider_iterations: 15
supervisor:
    childlogdir: data/supervisor_logs/
gearmand:
    enabled: yes
    listen: 127.0.0.1
    port: 4731
    threads: 0
    worker_wakeup: 0
corenlp:
    enabled: no
    annotator_url: ''
    annotator_timeout: 600
    annotator_level: ''
bitly:
    enabled: no
    access_token: ''
    timeout: 60
    json_read_stores:
        - postgresql
    json_write_stores:
        - postgresql
facebook:
    enabled: no
    app_id: ''
    app_secret: ''
    timeout: 60
