---
Plugin::Authentication:
    default_realm: users
    users:
        credential:
            class: Password
            password_field: password
            password_hash_type: SHA-256
            password_salt_len: 64
            password_type: salted_hash
        store:
            class: MediaWords
gearman:
    notifications:
        emails: []
        from_address: gjs@mediacloud.org
        subject_prefix: '[GJS]'
    worker_log_dir: data/gearman_worker_logs/
mail:
    bug_email: ''
    from_address: noreply@mediacloud.org
mediawords:
    always_show_stack_traces: no
    controversy_model_reps: 25
    default_home_page: admin/media/list
    disable_json_top_500_words_cache: no
    download_storage_locations:
        - postgresql
    extractor_method: CrfExtractor
    inline_java_jni: no
    language: en_US_and_ru_RU
    owner: mediacloud@cyber.law.harvard.edu
    read_file_downloads_from_gridfs: yes
    read_tar_downloads_from_gridfs: yes
    recaptcha_private_key: 6LfEVt0SAAAAABmI-8IJmx4g93eNcSeyeCxvLMs2
    recaptcha_public_key: 6LfEVt0SAAAAAFwQI0pOZ1bTHgDTpQcMeQY6VLd_
    solr_select_url: http://localhost:8983/solr/collection1/select
    user_agent: mediawords bot (http://cyber.law.harvard.edu)
supervisor:
    childlogdir: data/supervisor_logs/
gearmand:
    enabled: no
    listen: 127.0.0.1
    port: 4731
corenlp:
    enabled: no
    annotator_url: ''
    annotator_timeout: 600
